---
- name: Change user password
  hosts: all
  become: yes
  vars_prompt:
    - name: newpassword
      prompt: New password?
  tasks:
    - name: Change user password
      user:
        name: pi
        update_password: always
        password: "{{ newpassword|password_hash('sha512') }}"