---
- name: Setup hostname
  hosts: all
  become: yes
  tasks:
    - name: Ping test
      ping:

    - name: Set hostname
      hostname:
        name: "lucifer"

    - name: Update hosts file (127.0.0.1)
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1[ \t]+localhost'
        line: '127.0.0.1 localhost lucifer'
        state: present
    
    - name: Update hosts file (127.0.1.1)
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.1\.1[ \t]+raspberrypi'
        line: '127.0.1.1 localhost lucifer'
        state: present