version: '3'
services:
  netdata:
    image: netdata/netdata
    hostname: lucifer
    container_name: netdata
    environment:
      TZ: Asia/Kolkata
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
